### ISSUE TITLE
iPhoneX系列适配

### ISSUE THREAD

**Issue by sunjie19921111** [GodzzZZZ/MFHUDManager#2]
#define isIphoneX (statusHeight == 812)改为
#define statusHeight [UIApplication sharedApplication].statusBarFrame.size.height
#define isIphoneX (statusHeight == 44)

**Comment by 1ess** [comment]
@sunjie19921111 不好意思刚看到，现在好长时间不做 iOS 开发了，可以提个 PR，我合并一下
